[12/05/2022-10:44:03] [TRT] [E] 4: [graphShapeAnalyzer.cpp::processCheck::727] Error Code 4: Internal Error (IAssertionLayer (Unnamed Layer* 5) [Assertion]: condition[0] is false: 0. Edited message!)
[12/05/2022-10:44:03] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::738] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
Traceback (most recent call last):
  File "./AssertionLayer/Message.py", line 51, in <module>
    engine = trt.Runtime(logger).deserialize_cuda_engine(engineString)
TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

Invoked with: <tensorrt.tensorrt.Runtime object at 0x7f068e16c4b0>, None
